dist: trusty
sudo: false
language: go
go:
- 1.9

before_script:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    cd ../.. &&
    mv coveo terraform-providers &&
    cd terraform-providers/terraform-provider-kubernetes &&
    bash scripts/gogetcookie.sh &&
    go get ./...;
  fi

script:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    make test &&
    make vet;
  fi

# branches:
#   only:
#   - deployment-fork

matrix:
  fast_finish: true
  allow_failures:
  - go: tip

after_success:
- if [ ${TRAVIS_TAG::1} = v ];
  then
    curl -sL https://git.io/goreleaser | bash;
  fi
